### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by DampfWaffel** [Skylyxx/SkriptDocsGenerator#3] opened 2021-05-19 12:35 UTC
docs stop after skimage : (

![image](https://user-images.githubusercontent.com/19693397/118813192-30a77300-b8af-11eb-9cb1-0f435295722c.png)

```js
[14:33:37 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:33:37 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[14:33:37 INFO]: [Skript] Server Version: git-Purpur-1011 (MC: 1.16.5)
[14:33:37 INFO]: [Skript] Skript Version: 2.5.3
[14:33:37 INFO]: [Skript] Installed Skript Addons:
[14:33:37 INFO]: [Skript]  - SkImage v1.5
[14:33:37 INFO]: [Skript]  - reqn v1.3.0-alpha
[14:33:37 INFO]: [Skript]  - skript-reflect v2.2.1 (https://github.com/TPGamesNL/skript-reflect)
[14:33:37 INFO]: [Skript]  - SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee)
[14:33:37 INFO]: [Skript]  - SkriptJSON v1.0.0
[14:33:37 INFO]: [Skript]  - MundoSK v1.8.6-BETA.58 (https://forums.skunity.com/resources/mundosk.69/)
[14:33:37 INFO]: Brrrrr
[14:34:47 INFO]: Plugins (11): MundoSK*, NametagEdit*, ProtocolLib, reqn*, SkBee, SkImage*, Skript, skript-reflect*, SkriptDocsGenerator, SkriptHubDocsTool*, SkriptJSON*
```

**Comment by Skylyxx** [comment] 2021-05-25 16:54
Hi, the problem is not with SkImage because the success message is sended. If you use the stable release, the problem might be from skript-reflect that is quite special. Please try to use [this build](https://github.com/Skylyxx/SkriptDocsGenerator/actions/runs/832081716), it should be work. If it won't, an error message more explicit will be sended 😄 
Sorry for 6 days without response, but I was on hollydays 😓

**Comment by Skylyxx** [comment] 2021-05-29 08:15
Seems to not have response, I close the issue, if the message above doesn't fix your problem, you can re-open the issue, and tell me what's wrong.

**Comment by DampfWaffel** [comment] 2021-05-29 10:39
hey. :)
its seems that build work flawless.
but is there a way to docs the Skript Syntax itself? atm the only target are the Addons.

**Comment by Skylyxx** [comment] 2021-05-29 10:46
Hi, yes, I plan to add support for Skript's syntaxes in a future release. The next release will add the possibility to choose a specific addon. I will publish Skript's support for later.

**Comment by DampfWaffel** [comment] 2021-05-29 21:22
i've figured out. Some Syntaxes will be ignored.

with the SkriptHubDocsTool i've found the `ExprMemberPresence` but not with this SkriptDocsTool

https://drive.google.com/file/d/1evHCdg0I-3f0F6aof9c7jDP1IxvHrIRF/view?usp=sharing - SkriptHubDocs
https://drive.google.com/file/d/1dhwcPzG3J1qTPRnE6DgBIt09ufLWMpon/view?usp=sharing - SkriptDocsGenerator

have a great day

**Comment by Skylyxx** [comment] 2021-05-29 21:25
Could you upload files in pastebin or equivalent service please ? The google drive files are in restricted access.
TY

**Comment by Skylyxx** [comment] 2021-05-31 10:30
Hi, I encountered a similar problem as you, so after a lot of tests, I've found the problem. Can you, please, try [this build](https://github.com/Skylyxx/SkriptDocsGenerator/actions/runs/892597398) that should fix your problem.

**Comment by Skylyxx** [comment] 2021-06-04 17:01
I'm closing due to inactivity

**Closed as completed by Skylyxx** 2021-06-04 17:01 UTC
Labels: bug
